{
 "title": "CP-02",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Port_Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ionbridge_port_voltage{id=\"0\"}*ionbridge_port_current{id=\"0\"}/ 1e6",
     "legendFormat": "USB_A"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"1\"}*ionbridge_port_current{id=\"1\"}/ 1e6",
     "legendFormat": "USB_C1"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"2\"}*ionbridge_port_current{id=\"2\"}/ 1e6",
     "legendFormat": "USB_C2"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"3\"}*ionbridge_port_current{id=\"3\"}/ 1e6",
     "legendFormat": "USB_C3"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"4\"}*ionbridge_port_current{id=\"4\"}/ 1e6",
     "legendFormat": "USB_C4"
    }
   ]
  },
  {
   "title": "Total_Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    ionbridge_port_voltage{id=~\"[0-4]\"} \n    * \n    ionbridge_port_current{id=~\"[0-4]\"}\n  ) / 1e6\n)",
     "legendFormat": "Total_Power"
    }
   ]
  },
  {
   "title": "Port_Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ionbridge_port_voltage{id=\"0\"} / 1000",
     "legendFormat": "USB_A1"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"1\"} / 1000",
     "legendFormat": "USB_C1"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"2\"} / 1000",
     "legendFormat": "USB_C2"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"3\"} / 1000",
     "legendFormat": "USB_C3"
    },
    {
     "expr": "ionbridge_port_voltage{id=\"4\"} / 1000",
     "legendFormat": "USB_C4"
    }
   ]
  },
  {
   "title": "Port_Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "ionbridge_port_current{id=\"0\"} / 1000",
     "legendFormat": "USB_A1"
    },
    {
     "expr": "ionbridge_port_current{id=\"1\"} / 1000",
     "legendFormat": "USB_C1"
    },
    {
     "expr": "ionbridge_port_current{id=\"2\"} / 1000",
     "legendFormat": "USB_C2"
    },
    {
     "expr": "ionbridge_port_current{id=\"3\"} / 1000",
     "legendFormat": "USB_C3"
    },
    {
     "expr": "ionbridge_port_current{id=\"4\"} / 1000",
     "legendFormat": "USB_C4"
    }
   ]
  }
 ]
}